### ISSUE TITLE
store 링크 가져오는 법

### ISSUE THREAD

**Issue by KimGenius** [738/awesome-sushi#25]
안녕하세요! 제가 #24 이 작업을 할 때 다른 장소가 전부 네이버 스토어 링크로 되어있어서 맞추려고 찾아보았는데 너무 안나와서 (제가 못 찾는걸수도..) 결국 naver 지도에서 해당 장소의 id를 가져온 뒤 https://store.naver.com/restaurants/detail?id={장소ID} 이렇게 해서 링크를 첨부하였습니다.

https://user-images.githubusercontent.com/29722636/104144590-1e9c5c00-5407-11eb-83c3-589a8b832121.mov

혹시 이 방법이 맞나요?
아니면 더 편리한 방법이 있을까요??

감사합니다 :)

**Comment by 738** [comment]
네이버에서 장소를 검색하면 예전에는 플레이스로 넘어갔는데 지금은 지도로 넘어가는 것으로 변경되었더라구요 😅

우선 @KimGenius 님이 하신 방법이 제일 좋아보입니다 :)
기여 감사드립니다.

**Comment by KimGenius** [comment]
그럼 혹시 링크 가져오는 방법을 따로 기재하여 PR을 날려도 될까요??
@738 

다른분들은 잘 찾으실수도 있겠지만 저는 찾는데 굉장한 어려움을 겪어서요 ㅠㅠ

**Comment by 738** [comment]
@KimGenius 

넵 그럼요!
제가 [`CONTRIBUTING.md`](https://github.com/738/awesome-sushi/blob/master/CONTRIBUTING.md) 파일을 추가했는데 여기에 작성하면 좋을것 같습니다.
