### ISSUE TITLE
스시오오시마 링크 오류

### ISSUE THREAD

**Issue by Jeje01** [738/awesome-sushi#28]
가게 이름에 걸려있는 아래 링크로 pc에서 들어가면 거의 403 Forbidden 에러가 뜨네요.
모바일에서는 
```
요청하신 페이지를 찾을 수 없습니다.
방문하시려는 페이지의 주소가 잘못 입력되었거나,
페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.
```
라고 나오네요.
https://store.naver.com/restaurants/detail?id=<id>

**Comment by 738** [comment]
스시오오시마가 이전 예정이라 주소가 사라진것 같습니다. 스시오오시마 제외하고는 괜찮아보이네요.
스시오오시마는 수정하도록 하겠습니다 :)
