### ISSUE TITLE
스시오오시마 폐업했다는데요?

### ISSUE THREAD

**Issue by kdh8219** [738/awesome-sushi#56]
![image](https://user-images.githubusercontent.com/65698239/158002025-7199d34a-b567-4759-bd16-fda3a78f9785.png)

**Comment by 738** [comment]
@kdh8219 

찾아보니 성북동에서 다시 오픈했는데, 회원제로 운영중에 있다고 합니다. 목록에서 제거하도록 하겠습니다.
