### ISSUE TITLE
스시 사카우

### ISSUE THREAD

**Issue by leejseo** [738/awesome-sushi#6]
유튜브 등에서는 스시 사카우에 대해 좋은 평이 많은데, 이상하게 주변에 다녀온 사람들은 전부 안좋은 평을 하더라고요. 샤리와 네타 모든 부분에서 (가격에 비해) 완성도가 떨어진다고... 제가 확인할 수 있는 방법이 없는지라 실제로 가보신 분이 관련 내용을 추가해주면 좋겠습니다.

**Comment by seongminp** [comment]
안녕하세요. 저는 스시 사카우 3~4회 방문 했었는데 매번 만족스러웠습니다. 가성비면에서도 괜찮은 것 같습니다 (디너 88000). 스시 마츠모토 같은 곳의 정통 일본 스시랑은 좀 다르다고 하는데요, 입문자 입맛에는 딱 맞았습니다. 셰프분들이 마츠모토 셰프 밑에서 배우셨다고 하셨는데 사카우만의 재해석이 담긴 스시 구성이 많다는 느낌이었습니다.  

스시 이외의 장국 튀김 이런것도 저는 완전 만족했습니다!

예약은 전화하는 같은 주에는 어렵고 그 다음 주에는 웬만하면 할 수 있었습니다.
