### ISSUE TITLE
분류 기준

### ISSUE THREAD

**Issue by leejseo** [738/awesome-sushi#8]
이 리파지토리가 가격대별로 스시야들을 분류하는 만큼 엔트리급/미들급/하이엔드급을 분류하는 기준을 명시해주는 편이 장기적인 리파지토리 관리에 도움이 될 수 있을듯 합니다.

**Comment by 738** [comment]
넵 문서에 추가하도록 하겠습니다.

제가 생각하는 기준은

`엔트리급`

- 런치 ~5만원
- 디너 ~10만원

`미들급`

- 런치 5만원 ~ 10만원
- 디너 10만원 ~ 20만원

`하이엔드급`

- 런치 10만원 ~
- 디너 20만원 ~

입니다. 

다른 의견 있으시면 말씀해주세요! :)
